# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync.xci
# IP: The module: 'clk_sync' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync.xci
# IP: The module: 'clk_sync' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Work/vivado_project/MiniMIPS32_Lite_FullSyS/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/clk_sync/clk_sync_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
